Reset Button
mutualmobile/Barricade pull request #26
Opened 2017-04-10 07:03 UTC by suchoX

1. Added Reset Button in Barricade Activity
2. Added Delay reset in Barricade

2017-04-10 11:47 UTC, tushar-nallan approved these changes

2017-04-10 11:47 UTC, tushar-acharya commented on barricade/src/main/java/com/mutualmobile/barricade/activity/BarricadeActivity.java
> +    } else if (itemId == R.id.menu_reset) {
Use switch case

2017-04-10 11:47 UTC, tushar-acharya commented on barricade/src/main/java/com/mutualmobile/barricade/activity/BarricadeActivity.java
> +    AlertDialog.Builder builder = new AlertDialog.Builder(this);
Continue the builder. Also .show() internally calls .create() so no need of that

2017-04-10 11:47 UTC, tushar-acharya commented on barricade/src/main/res/drawable/ic_reset.xml
> +<vector xmlns:android="http://schemas.android.com/apk/res/android"
@mustafa01ali Do we want to make it mandatory for the user of this library to have vector support or should we use image drawables? Currently we have 2 vector drawables - red tick mark, and timer icon.

2017-04-10 14:17 UTC, suchoX commented on barricade/src/main/java/com/mutualmobile/barricade/activity/BarricadeActivity.java
> +    } else if (itemId == R.id.menu_reset) {
Switch Case doesnt work anymore in this case

2017-04-11 05:19 UTC, mustafa01ali requested changes

2017-04-11 05:19 UTC, mustafa01ali commented on barricade/src/main/java/com/mutualmobile/barricade/activity/BarricadeActivity.java
> +        .setNeutralButton(R.string.ok, new DialogInterface.OnClickListener() {
Replace with positive and negative buttons

2017-04-11 05:19 UTC, mustafa01ali commented on barricade/src/main/res/values/strings.xml
> +  <string name="reset_message">Are You sure you want to reset settings?</string>
Replace with `Are you sure you want to reset all changes?`

2017-04-11 05:19 UTC, mustafa01ali commented on barricade/src/main/res/menu/main.xml
> +      android:title="@string/menu_delay"/>
Add a proper title

2017-04-11 05:19 UTC, mustafa01ali commented on barricade/src/main/res/drawable/ic_reset.xml
> +<vector xmlns:android="http://schemas.android.com/apk/res/android"
This icon is misleading, replace with https://material.io/icons/#ic_undo

2017-04-11 05:19 UTC, mustafa01ali commented on barricade/src/main/res/drawable/ic_reset.xml
> +<vector xmlns:android="http://schemas.android.com/apk/res/android"
Yes, every app should ideally adopt vector drawables at this point. If we can push folks to adopt it, why not.

2017-04-11 05:22 UTC, mustafa01ali approved these changes

2017-04-11 05:39 UTC, merged