(WIP) Added code to initiate Espresso tests in CI
mutualmobile/Barricade pull request #44
Opened 2017-04-19 07:57 UTC by suchoX

2017-04-20 03:41 UTC, tushar-nallan approved these changes

2017-04-20 03:41 UTC, tushar-acharya commented on .travis.yml
> +    - sys-img-armeabi-v7a-android-19
Can you check if the performance increases if you use an x86 or x64 image?

2017-04-21 13:27 UTC, mustafa01ali requested changes

2017-04-21 13:27 UTC, mustafa01ali commented on .travis.yml
> +before_script:
Make this run only for Mrs

2017-05-02 08:42 UTC, suchoX commented on .travis.yml
> +before_script:
Done

2017-05-05 17:59 UTC, mustafa01ali approved these changes

2017-05-06 14:43 UTC, merged